apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-server
  template:
    metadata:
      labels:
        app: python-server
    spec:
      containers:
      - name: python-server
        image: harshitakathuria/python-server:latest
        ports:
        - containerPort: 5000
