apiVersion: v1
kind: Service
metadata:
  name: python-server-service
spec:
  selector:
    app: python-server-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
